### ISSUE TITLE
Support for RHEL 7

### ISSUE THREAD

**Issue by felipe1982** [BashtonLtd/puppet-timezone#18]
Red hat now uses a new timezone command and is no longer using sysconfig/clock. I would make the changes myself if I were good at module writing.  Thank you

**Comment by bashtoni** [comment]
You're correct in that `/etc/sysconfig/clock` is no longer used in EL7.  However, `timedatectl` is just setting the symlinks to `/etc/localtime` anyway, so the module functions as expected.
